(()=>{
  const P=window.PROBLEMS||[],groups=window.COMBINED_GROUPS||[],roadmap=window.ROADMAP_STAGES||[],platforms=window.PLATFORMS||[],page=document.body.dataset.page;
  const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const idOf=x=>(x.url.match(/[?&]problemid=([^&]+)/)||[])[1];
  const byKey=new Map(P.map(x=>[x.key,x]));
  const statHtml=pairs=>pairs.map(([label,value])=>'<div class="stat"><b>'+value+'</b><span>'+label+'</span></div>').join('');
  const levelRank=x=>Number(String(x.level||'L9').slice(1))||9;
  function stats(items){const topics=new Set(items.map(x=>x.topic)).size,basic=items.filter(x=>levelRank(x)<=2).length;return statHtml([['唯一題目',items.length],['主題',topics],['L1–L2',basic],['L3–L5',items.length-basic]])}
  function row(x,i){return '<tr><td class="order">'+i+'</td><td><a class="title" target="_blank" rel="noopener" href="'+x.url+'">'+esc(x.title)+'</a></td><td>'+esc(x.topic)+'<span class="sub">'+esc(x.subtopic||'')+'</span></td><td><span class="pill">'+esc(x.level)+'</span></td><td>'+esc(x.difficulty||x.type||'—')+'</td><td>'+esc(x.minutes)+' 分</td></tr>'}
  function table(items){return '<div class="table-wrap"><table><thead><tr><th>順序</th><th>題目</th><th>主題</th><th>階段</th><th>難度</th><th>限時</th></tr></thead><tbody>'+items.map((x,i)=>row(x,i+1)).join('')+'</tbody></table></div>'}
  function filtered(items){const q=(document.querySelector('#search')?.value||'').trim().toLowerCase(),l=document.querySelector('#level')?.value||'all';return items.filter(x=>(l==='all'||x.level===l)&&(!q||[x.title,x.topic,x.subtopic,x.difficulty,x.method].join(' ').toLowerCase().includes(q)))}
  function section(id,name,desc,items){return '<section class="method" id="'+id+'"><div class="method-head"><div><h2>'+esc(name)+'</h2><p>'+esc(desc)+'</p></div><span>'+items.length+' 題</span></div>'+table(items)+'</section>'}
  function moduleDetails(id,name,desc,items,open){return '<details class="roadmap-module" id="'+id+'" '+(open?'open':'')+'><summary><div><h3>'+esc(name)+'</h3><p>'+esc(desc)+'</p></div><span>'+items.length+' 題</span></summary>'+table(items)+'</details>'}
  function setToc(entries){const root=document.querySelector('#tocLinks');if(!root)return;root.innerHTML=entries.map(([id,label])=>'<a href="#'+id+'">'+esc(label)+'</a>').join('');root.querySelectorAll('a').forEach(a=>a.onclick=()=>{const target=document.querySelector(a.getAttribute('href'));if(target?.tagName==='DETAILS')target.open=true;if(innerWidth<=850)document.body.classList.add('toc-collapsed')})}
  function renderRoadmap(){let shown=0,html='',toc=[];const hasFilter=(document.querySelector('#search')?.value||'').trim()||(document.querySelector('#level')?.value||'all')!=='all';roadmap.forEach((stage,si)=>{let modules='',moduleToc=[];stage.modules.forEach(m=>{const rows=filtered(m.keys.map(k=>byKey.get(k)).filter(Boolean));if(!rows.length)return;shown+=rows.length;const id='roadmap-'+stage.id+'-'+m.id;moduleToc.push([id,'　'+m.name]);modules+='<details class="roadmap-module" id="'+id+'" '+(hasFilter||si===0&&m.id==='io'?'open':'')+'><summary><div><h3>'+esc(m.name)+'</h3><p>'+esc(m.desc)+'</p></div><span>'+rows.length+' 題</span></summary>'+table(rows)+'</details>'});if(modules){const sid='stage-'+stage.id;toc.push([sid,stage.name],...moduleToc);html+='<section class="roadmap-stage" id="'+sid+'"><header class="stage-head"><div><h2>'+esc(stage.name)+'</h2><p>'+esc(stage.desc)+'</p></div><span class="stage-level">'+esc(stage.level)+'</span></header>'+modules+'</section>'}});document.querySelector('#roadmapRoot').innerHTML=html+'<p class="source-note">課綱層級參考 USACO Guide；題目依本題庫主題與難度重新映射。</p>';document.querySelector('#summary').innerHTML=statHtml([['唯一題目',shown],['階段',roadmap.length],['模組',roadmap.reduce((n,s)=>n+s.modules.length,0)],['平台',platforms.length]]);document.querySelector('#empty').style.display=shown?'none':'block';setToc(toc)}
  function render(){const platform=document.body.dataset.platform,items=P.filter(x=>x.platform===platform),rows=filtered(items),hasFilter=(document.querySelector('#search')?.value||'').trim()||(document.querySelector('#level')?.value||'all')!=='all';document.querySelector('#summary').innerHTML=stats(items);let html='',toc=[],opened=false;if(platform==='ZeroJudge'){groups.forEach(g=>{const ids=new Set(g.ids),part=rows.filter(x=>ids.has(idOf(x)));if(part.length){const sid='group-'+g.id,isOpen=hasFilter||!opened;html+=moduleDetails(sid,g.name,g.desc,part,isOpen);toc.push([sid,g.name]);opened=true}})}else{const visible=new Set(rows.map(x=>x.key));roadmap.forEach(stage=>{let modules='',moduleToc=[];stage.modules.forEach(m=>{const part=m.keys.map(k=>byKey.get(k)).filter(x=>x&&x.platform===platform&&visible.has(x.key));if(!part.length)return;const id='platform-'+platform.toLowerCase()+'-'+stage.id+'-'+m.id,isOpen=hasFilter||!opened;modules+=moduleDetails(id,m.name,m.desc,part,isOpen);moduleToc.push([id,'　'+m.name]);opened=true});if(modules){const sid='platform-'+platform.toLowerCase()+'-'+stage.id;html+='<section class="roadmap-stage" id="'+sid+'"><header class="stage-head"><div><h2>'+esc(stage.name)+'</h2><p>'+esc(stage.desc)+'</p></div><span class="stage-level">'+esc(stage.level)+'</span></header>'+modules+'</section>';toc.push([sid,stage.name],...moduleToc)}})}document.querySelector('#problemRoot').innerHTML=html;document.querySelector('#empty').style.display=rows.length?'none':'block';setToc(toc)}
  function setupToc(){document.querySelector('#tocClose')?.addEventListener('click',()=>document.body.classList.add('toc-collapsed'));document.querySelector('#tocOpen')?.addEventListener('click',()=>document.body.classList.remove('toc-collapsed'));if(innerWidth<=850)document.body.classList.add('toc-collapsed')}
  setupToc();
  if(page==='roadmap'){renderRoadmap();['search','level'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='search'?'input':'change',renderRoadmap))}
  else{render();['search','level'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='search'?'input':'change',render))}
})();